spring:
    application:
        name: "backend"

    datasource:
        url: "jdbc:mysql://${DB_ENDPOINT}:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
        username: "${DB_USERNAME}"
        password: "${DB_PASSWORD}"
        driver-class-name: "com.mysql.cj.jdbc.Driver"

    data:
        redis:
            host: "${REDIS_HOST}"
            port: "${REDIS_PORT}"

    mail:
        host: "${EMAIL_HOST}"
        port: "${EMAIL_PORT}"
        username: "${EMAIL_USERNAME}"
        password: "${EMAIL_PASSWORD}"
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

mybatis:
    type-aliases-package: com.demo.damulTalk.**.domain
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true

jwt:
    secret: "${JWT_SECRET}"
    access-token-expiration: "${ACCESS_TOKEN_EXPIRATION}"
    refresh-token-expiration: "${REFRESH_TOKEN_EXPIRATION}"
    temporary-token-expiration: "${TEMPORARY_TOKEN_EXPIRATION}"

frontend:
    url: "${FRONTEND_URL}"

logo:
    image:
        url: "${LOGO_URL}"