name: DamulTalk CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      frontend: ${{ steps.frontend.outputs.changed }}
      backend: ${{ steps.backend.outputs.changed }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Detect Frontend Changes
        id: frontend
        run: |
          if git diff --name-only origin/main...HEAD | grep '^frontend/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Detect Backend Changes
        id: backend
        run: |
          if git diff --name-only origin/main...HEAD | grep '^backend/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - run: cd frontend && pnpm install
      - run: cd frontend && pnpm run lint
      - run: cd frontend && pnpm run test
      - run: cd frontend && pnpm run build

  backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Test with Gradle
        run: cd backend && ./gradlew test

      - name: Build with Gradle
        run: cd backend && ./gradlew clean build